SRCS:=$(wildcard *.c)                                                                                                                                                                                          
server:$(SRCS)
	gcc  $^ -o $@ 
clean:
	rm -rf server
