SRCS:=$(wildcard *.c)                                                                                                                                                                                          
client:$(SRCS)
	$(CC) $^ -o $@ 
clean:
	rm -rf client
